### ISSUE TITLE
Multiple misspellings

### ISSUE THREAD

**Issue by hugotoledo** [osu-slam/osu-slam.github.io#1]
Hello!

I first noticed _aphasia_ misspelled as _aphaisa_ on  https://osu-slam.github.io/projects.html. On searching your repo, I see three such misspellings.

Also on that same page I saw _Cochlea_ Implant rather than _Cochlear_ Implant, as is used elsewhere in that subject area.

That's it.  I hope this helps.

Hugo

**Comment by HeardMatthew** [comment]
Thanks for pointing out these errors! I just took over as webmaster. Taking a look at the website it appears that your first comment made it into the website but not the second one.
